export enum Technologies {
  REACT = "REACT",
  JAVASCRIPT = "JAVASCRIPT",
  TYPESCRIPT = "TYPESCRIPT",
  SWIFT = "SWIFT",
  JAVA = "JAVA",
  PYTHON = "PYTHON",
  NODEJS = "NODEJS",
  HTML = "HTML",
  CSS = "CSS",
  VISUAL_BASIC = "VISUAL_BASIC",
  CPP = "CPP", // C++
  RETHINKDB = "RETHINKDB",
  REDIS = "REDIS",
  CSHARP = "CSHARP",
  MONGODB = "MONGODB",
  EFCORE = "EFCORE",
}

export enum TechnologiesNames {
  REACT = "React",
  JAVASCRIPT = "JavaScript",
  TYPESCRIPT = "TypeScript",
  SWIFT = "Swift",
  JAVA = "Java",
  PYTHON = "Python",
  NODEJS = "Node.js",
  HTML = "HTML",
  CSS = "CSS",
  VISUAL_BASIC = "Visual Basic",
  CPP = "C++",
  RETHINKDB = "RethinkDB",
  REDIS = "Redis",
  CSHARP = "C#",
  MONGODB = "MongoDB",
  EFCORE = "EF Core",
}

export enum TechnologiesColors {
  REACT = "#26a69a",
  JAVASCRIPT = "#ff9800",
  JAVA = "#f89820",
  SWIFT = "#F05138",
  TYPESCRIPT = "#007acc",
  PYTHON = "#1976d2",
  NODEJS = "#66bb6a",
  HTML = "#ef5350",
  CSS = "#673ab7",
  VISUAL_BASIC = "#ba68c8",
  CPP = "#ec407a",
  RETHINKDB = "#007acc",
  REDIS = "#D82C20",
  CSHARP = "#239120",
  MONGODB = "#47A248",
  EFCORE = "#512BD4",
}
