FROM node:22-alpine AS base
RUN npm install -g bun

FROM base AS deps
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1

# Build args for NEXT_PUBLIC_* vars (Coolify passes these automatically)
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_CLERK_SIGN_IN_URL
ARG NEXT_PUBLIC_CLERK_SIGN_UP_URL
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
ARG NEXT_PUBLIC_GITHUB_REPO_NAME
ARG NEXT_PUBLIC_GITHUB_REPO_OWNER
ARG NEXT_PUBLIC_STATSIG_CLIENT_KEY
ARG NEXT_PUBLIC_LIVEKIT_URL
ARG NEXT_PUBLIC_HYPERTUNE_TOKEN
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_STRIPE_PRICE_SL1_MONTHLY
ARG NEXT_PUBLIC_STRIPE_PRICE_SL1_ANNUAL
ARG NEXT_PUBLIC_STRIPE_PRICE_SL1_LIFETIME
ARG NEXT_PUBLIC_STRIPE_PRICE_SL2_MONTHLY
ARG NEXT_PUBLIC_STRIPE_PRICE_SL2_ANNUAL
ARG NEXT_PUBLIC_STRIPE_PRICE_SL2_LIFETIME
ARG NEXT_PUBLIC_CONVEX_URL

# Also need server-side env vars that are used at build time (e.g. by drizzle/db imports)
ARG DATABASE_URL
ARG CLERK_SECRET_KEY

RUN bun run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
USER nextjs
EXPOSE 3000
ENV PORT=3000 HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
